services:
  # bot:
  #   build: .
  #   container_name: "discord-rbot"
  #   ports:
  #     - 8080:8080
  #   env_file: .env

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weirdAssPasword1
      POSTGRES_DB: discordbot
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
